#include "DIGILib.h"
#include <string>

//DIGIMUSER::DIGIMUSER(){
//TODO autogenerated constructior stub
//}

//for gain A1
int pot1 = 15;
int gainNum = 0;

void DIGIMUSER :: dSetup(void)
{

  //std::cout << "Setting up" << std::endl;
  //list

  //int potentiometer2 = #;//tentative
  //int RotSwitch = #;

  //pin setup
  //int LED = ;
  pinMode(pot1, INPUT);
  //setup
  //digitalWrite(,LOW);

};

int DIGIMUSER::getGain() {

  return analogRead(pot1);

}//mixer1.gain
