#include "DIGILib.h"

DIGIMUSER::DIGIMUSER(){
		//TODO autogenerated constructior stub
}


void DIGIMUSER :: dSetup(void)
{
	
	std::cout << "Setting up" << std::endl;
	//list 
	int potentiometer1 = #;//for gain
	int potentiometer2 = #;//tentative
	int RotSwitch = #;
	
	//pin setup
	int LED = ;
	pinMode(potentiometer, INPUT);
	setup
	digitalWrite(,LOW);
	
};

void doSomething(){
	
}