#include "DIGILib.h"
#include <string>

//DIGIMUSER::DIGIMUSER(){
//TODO autogenerated constructior stub
//}

//for gain A1
int pot1 = 22;//A8
int pot2 = 19;//A5
int gainNum = 0;

void DIGIMUSER :: dSetup(void)
{

  //std::cout << "Setting up" << std::endl;
  //list

  //int potentiometer2 = #;//tentative
  //int RotSwitch = #;

  //pin setup
  //int LED = ;
  pinMode(pot1, INPUT);
  pinMode(pot2, INPUT);
  //setup
  //digitalWrite(,LOW);

};

int DIGIMUSER::getGain() {

  return analogRead(pot1);

}//mixer1.gain


/*
void adc_setup(){
	//DIDR0
	//DIDR2
	
	//print errors
	
	
	
	// Print errors, if any.
    if(adc->adc0->fail_flag != ADC_ERROR::CLEAR) {
      Serial.print("ADC0: "); Serial.println(getStringADCError(adc->adc0->fail_flag));
    }
	adc->resetError();
	
}
*/







